---
title: "About This Website"
output: 
  html_document:
    theme: cosmo
---

The titles of the projects contained in this portfolio are listed below to help convey the nature of the contents of this portfolio.

Portfolio 1 - Graphing the Effect of Intergroup Contact on Political Polarization

Portfolio 2 - A Somewhat Complicated Case of Wide-to-Long

Portfolio 3 - Exploring Effective Data Visualization

Portfolio 4 - Data Cleaning

Portfolio 5 - Using Functions and Loops to Compile Many Regression Analyses

Portfolio 6 - Function for Regression Output Table

Portfolio 7 - Cross-Referencing and Combining Datasets

Portfolio 8 - Study 2 Results

Portfolio 9 - Confirmatory Factor Analysis

Portfolio 10 - Creating a Cross-Cultural Interviewee Demographics Presentation


The first three projects use data from a first-year project study from my master's program in psychology. It was an experimental study looking at the effects of intergroup contact and deliberation on affective political polarization. The projects document my learning to graph in R, learning to restructure data in R, and learning to consider principles of effective data visualizaiton.

Projects 4, 5, 6, 8, and 9 are related to my master's thesis study which invovled validating a scale for measuring critical social justice attitudes and measuring their association with well-being. Project 4 documents my learning how to do data cleaning in R. Projects 5 and 6 demonstrate my learning how to use functions to effectively compile and evaluate the output of many data analyses (mostly regression analyses). Project 8 demonstrates my learning how to use R to effectively organize and present (almost) the entirety of the data analyses and results for a study from my thesis. And project 9 demonstrates my learning how to conduct confirmatory factor analyses in R.

Projects 7 and 10 were instances in which R came in handy for tasks I was asked to do as part of my Teaching Assistant duties while in my master's program. Project 7 demonstrates my learning how to cross reference datasets, combine them based on a common variable, and create a new dataset containing the desired variables from each original dataset; this was a sort of administrative task for which I found that R was the best way to accomplish the job quickly. Lastly, project 10 demonstrates my learning how to use R to create a presentation for use in a classroom setting and involved creating a pretty cool plot of a world map.
