<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 9 - Confirmatory Factor Analysis</title>

<script src="site_libs/header-attrs-2.29/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
<li>
  <a href="p08.html">Portfolio 8</a>
</li>
<li>
  <a href="p09.html">Portfolio 9</a>
</li>
<li>
  <a href="p10.html">Portfolio 10</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Portfolio 9 - Confirmatory Factor
Analysis</h1>

</div>


<div id="goal" class="section level2">
<h2>Goal</h2>
<blockquote>
<p>The goal of this project is to run a confirmatory factor analysis
(CFA) on the a seven-item critical social justice attitudes scale
(CSJAS) which was previosuly created using exploratory factor analysis
(EFA) in SPSS. I also run a CFA on another seven-item scale used in the
study, the GAD-7 anxiety scale, to compare the fit indices.</p>
</blockquote>
<blockquote>
<p>The data is from 149 undergraduates. The CFA is run on a randomly
split half of the sample.</p>
</blockquote>
<blockquote>
<p>The final product is the interpretation of the CFA which was used in
the write-up of this study.</p>
</blockquote>
</div>
<div id="loading-data-and-packages" class="section level2">
<h2>Loading data and packages</h2>
<pre class="r"><code>library(haven)
DataForAnalysis &lt;- read_sav(&quot;data/DataForAnalysis.sav&quot;)
library(rsample)
library(lavaan)</code></pre>
<pre><code>## This is lavaan 0.6-19
## lavaan is FREE software! Please report any bugs.</code></pre>
</div>
<div id="setting-seed-and-splitting-data" class="section level2">
<h2>Setting seed and splitting data</h2>
<p>Note: Claude.ai assisted in creating the code for this project.</p>
<pre class="r"><code># Set a seed for reproducibility
set.seed(1234)

# Create an initial split with 50/50 proportion
data_split &lt;- initial_split(DataForAnalysis, prop = 0.5)

# Save training data
EFA_data &lt;- training(data_split)
dim(EFA_data)</code></pre>
<pre><code>## [1]  73 108</code></pre>
<pre class="r"><code># Save testing data
CFA_data &lt;- testing(data_split)
dim(CFA_data)</code></pre>
<pre><code>## [1]  74 108</code></pre>
<pre class="r"><code>#Write out EFA data to replicate EFA in SPSS.
#write_sav(EFA_data, &quot;EFA_data.sav&quot;)</code></pre>
</div>
<div id="conducting-cfa" class="section level2">
<h2>Conducting CFA</h2>
<pre class="r"><code># Define your CFA model with a different name for the latent factor
cfa_model &lt;- &#39;
  # Define one-factor structure with a different name
  CSJAS_Factor =~ CSJAS1 + CSJAS2 + CSJAS4r + CSJAS10 + CSJAS15r + CSJAS17 + CSJAS28
&#39;

# Fit the CFA model using maximum likelihood estimation
cfa_fit &lt;- cfa(cfa_model, 
               data = CFA_data, 
               estimator = &quot;ML&quot;)  # ML for maximum likelihood

# Get a summary of the results
summary(cfa_fit, fit.measures = TRUE, standardized = TRUE)</code></pre>
<pre><code>## lavaan 0.6-19 ended normally after 21 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        14
## 
##   Number of observations                            74
## 
## Model Test User Model:
##                                                       
##   Test statistic                                18.323
##   Degrees of freedom                                14
##   P-value (Chi-square)                           0.192
## 
## Model Test Baseline Model:
## 
##   Test statistic                               276.945
##   Degrees of freedom                                21
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.983
##   Tucker-Lewis Index (TLI)                       0.975
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -672.204
##   Loglikelihood unrestricted model (H1)             NA
##                                                       
##   Akaike (AIC)                                1372.407
##   Bayesian (BIC)                              1404.664
##   Sample-size adjusted Bayesian (SABIC)       1360.545
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.065
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.137
##   P-value H_0: RMSEA &lt;= 0.050                    0.347
##   P-value H_0: RMSEA &gt;= 0.080                    0.417
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.041
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   CSJAS_Factor =~                                                       
##     CSJAS1            1.000                               0.839    0.775
##     CSJAS2            0.840    0.149    5.637    0.000    0.704    0.644
##     CSJAS4r           1.119    0.153    7.308    0.000    0.938    0.804
##     CSJAS10           0.805    0.141    5.727    0.000    0.675    0.653
##     CSJAS15r          1.455    0.180    8.094    0.000    1.220    0.879
##     CSJAS17           0.971    0.164    5.934    0.000    0.814    0.674
##     CSJAS28           0.898    0.137    6.548    0.000    0.753    0.733
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .CSJAS1            0.467    0.091    5.160    0.000    0.467    0.399
##    .CSJAS2            0.700    0.124    5.655    0.000    0.700    0.585
##    .CSJAS4r           0.480    0.097    4.952    0.000    0.480    0.353
##    .CSJAS10           0.613    0.109    5.633    0.000    0.613    0.574
##    .CSJAS15r          0.438    0.109    3.999    0.000    0.438    0.227
##    .CSJAS17           0.798    0.143    5.580    0.000    0.798    0.546
##    .CSJAS28           0.487    0.091    5.375    0.000    0.487    0.462
##     CSJAS_Factor      0.703    0.183    3.847    0.000    1.000    1.000</code></pre>
</div>
<div id="conducting-comparison-cfa" class="section level2">
<h2>Conducting Comparison CFA</h2>
<pre class="r"><code># CFA for GAD-7 for comparison
cfa_model2 &lt;-
  &#39;GAD7 =~ Q42_1 + Q42_2 + Q42_3 + Q42_4 + Q42_5 + Q42_6 + Q42_7&#39;

cfa_fit2 &lt;- cfa(cfa_model2, 
               data = CFA_data, 
               estimator = &quot;ML&quot;)

# Get a summary of the results
summary(cfa_fit2, fit.measures = TRUE, standardized = TRUE)</code></pre>
<pre><code>## lavaan 0.6-19 ended normally after 26 iterations
## 
##   Estimator                                         ML
##   Optimization method                           NLMINB
##   Number of model parameters                        14
## 
##                                                   Used       Total
##   Number of observations                            72          74
## 
## Model Test User Model:
##                                                       
##   Test statistic                                22.402
##   Degrees of freedom                                14
##   P-value (Chi-square)                           0.071
## 
## Model Test Baseline Model:
## 
##   Test statistic                               419.847
##   Degrees of freedom                                21
##   P-value                                        0.000
## 
## User Model versus Baseline Model:
## 
##   Comparative Fit Index (CFI)                    0.979
##   Tucker-Lewis Index (TLI)                       0.968
## 
## Loglikelihood and Information Criteria:
## 
##   Loglikelihood user model (H0)               -478.440
##   Loglikelihood unrestricted model (H1)             NA
##                                                       
##   Akaike (AIC)                                 984.881
##   Bayesian (BIC)                              1016.754
##   Sample-size adjusted Bayesian (SABIC)        972.645
## 
## Root Mean Square Error of Approximation:
## 
##   RMSEA                                          0.091
##   90 Percent confidence interval - lower         0.000
##   90 Percent confidence interval - upper         0.159
##   P-value H_0: RMSEA &lt;= 0.050                    0.164
##   P-value H_0: RMSEA &gt;= 0.080                    0.644
## 
## Standardized Root Mean Square Residual:
## 
##   SRMR                                           0.046
## 
## Parameter Estimates:
## 
##   Standard errors                             Standard
##   Information                                 Expected
##   Information saturated (h1) model          Structured
## 
## Latent Variables:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##   GAD7 =~                                                               
##     Q42_1             1.000                               0.837    0.871
##     Q42_2             1.110    0.092   12.054    0.000    0.929    0.937
##     Q42_3             1.107    0.099   11.146    0.000    0.926    0.905
##     Q42_4             1.005    0.095   10.626    0.000    0.841    0.884
##     Q42_5             0.797    0.103    7.705    0.000    0.667    0.739
##     Q42_6             0.554    0.110    5.061    0.000    0.464    0.546
##     Q42_7             0.708    0.097    7.297    0.000    0.593    0.714
## 
## Variances:
##                    Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
##    .Q42_1             0.223    0.044    5.081    0.000    0.223    0.241
##    .Q42_2             0.119    0.031    3.869    0.000    0.119    0.121
##    .Q42_3             0.191    0.041    4.670    0.000    0.191    0.182
##    .Q42_4             0.197    0.040    4.948    0.000    0.197    0.218
##    .Q42_5             0.369    0.065    5.655    0.000    0.369    0.453
##    .Q42_6             0.507    0.086    5.879    0.000    0.507    0.702
##    .Q42_7             0.338    0.059    5.703    0.000    0.338    0.491
##     GAD7              0.700    0.151    4.636    0.000    1.000    1.000</code></pre>
</div>
<div id="interpretation-excerpt-from-results-section-of-thesis"
class="section level2">
<h2>Interpretation: Excerpt from Results Section of Thesis</h2>
<blockquote>
<p>The final seven-item scale had factor loadings ranging from .60 to
.77 and a single factor explaining 47.1% of variance and alpha = .86.
CFA was performed on a randomly split half of the sample and indicated
excellent fit: CFI = 0.98, TLI = 0.98, RMSEA = 0.07, SRMR = 0.04, χ²
(14, 74) = 18.32 (p = 0.192). For comparison, the commonly-used measure
of anxiety, the GAD-7 (Spitzer et al., 2006), which is also a seven-item
scale, had CFI = 0.98, TLI = 0.97, RMSEA = 0.09, SRMR = 0.05, χ² (14,
72) = 22.40 (p = 0.071), a slightly worse fit, on the same randomly
split half of the sample.</p>
</blockquote>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
